package model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("accesstokens", "id", Accesstokens.class);
		arp.addMapping("app_fields", "id", AppFields.class);
		arp.addMapping("app_settings", "id", AppSettings.class);
		arp.addMapping("apps", "id", Apps.class);
		arp.addMapping("client_trusted_domains", "id", ClientTrustedDomains.class);
		arp.addMapping("clients", "id", Clients.class);
		arp.addMapping("invites", "id", Invites.class);
		arp.addMapping("migrations", "id", Migrations.class);
		arp.addMapping("permissions", "id", Permissions.class);
		arp.addMapping("permissions_apps", "id", PermissionsApps.class);
		arp.addMapping("permissions_roles", "id", PermissionsRoles.class);
		arp.addMapping("permissions_users", "id", PermissionsUsers.class);
		arp.addMapping("posts", "id", Posts.class);
		arp.addMapping("posts_tags", "id", PostsTags.class);
		arp.addMapping("refreshtokens", "id", Refreshtokens.class);
		arp.addMapping("roles", "id", Roles.class);
		arp.addMapping("roles_users", "id", RolesUsers.class);
		arp.addMapping("settings", "id", Settings.class);
		arp.addMapping("subscribers", "id", Subscribers.class);
		arp.addMapping("tags", "id", Tags.class);
		arp.addMapping("users", "id", Users.class);
	}
}

