package model;

import com.james.springboot.BaseClientTrustedDomains;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientTrustedDomains extends BaseClientTrustedDomains<ClientTrustedDomains> {
	
}
