package model;

import com.james.springboot.BasePermissionsApps;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PermissionsApps extends BasePermissionsApps<PermissionsApps> {
	
}
