package model;

import com.james.springboot.BasePermissionsRoles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PermissionsRoles extends BasePermissionsRoles<PermissionsRoles> {
	
}
