package model;

import com.james.springboot.BasePermissionsUsers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PermissionsUsers extends BasePermissionsUsers<PermissionsUsers> {
	
}
