ALTER TABLE `casbin_rule` CHANGE `ptype` `ptype` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;

ALTER TABLE `casbin_rule` CHANGE `v0` `v0` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;